linear_regression: {}

ridge:
  alpha: [0.1, 1.0, 10.0]

lasso:
  alpha: [0.1, 1.0, 10.0]

decision_tree_regressor:
  max_depth: [null, 10, 20, 30]
  min_samples_split: [2, 5, 10]

random_forest_regressor:
  n_estimators: [50, 100, 200]
  max_depth: [null, 10, 20]
  min_samples_split: [2, 5, 10]

gradient_boosting_regressor:
  n_estimators: [50, 100, 200]
  learning_rate: [0.01, 0.1, 0.2]
  max_depth: [3, 5, 7]

svr:
  kernel: ["linear", "rbf"]
  C: [0.1, 1, 10]
  gamma: ["scale", "auto"]

k_neighbors_regressor:
  n_neighbors: [3, 5, 7]
  weights: ["uniform", "distance"]

xgb_regressor:
  n_estimators: [100, 200, 300]      
  learning_rate: [0.01, 0.1, 0.2]     
  max_depth: [3, 5, 7]                
  gamma: [0, 0.1, 0.3]                

